AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  RESTful API endpoint o read and write to Dynamo
Resources:
  crudemployeeslambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: >-
         RESTful API endpoint o read and write to Dynamo
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::488181570562:role/service-role/crud-employees-rol'
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint
